#!/bin/bash

run () {
    echo '-----' "$@" '-----'
    if ! "$@"
    then
        echo '----- PUZZLE FAILED -----'
        exit 1
    fi
}

{   run ./01a
    run ./01b
    run ./02a
    run ./02b
    run ./03
    run ./04-1
    run ./04-2
    run ./05a
    run ./05b
    run ./06
    run ./07a test-07a-1.txt
    run ./07a test-07a-2.txt
    run ./07a test-07a-3.txt
    run ./07a
    run ./07b test-07b-1.txt
    run ./07b test-07b-2.txt
    run ./07b
} >regressed-output.txt

if ! diff -u puzzle-output.txt regressed-output.txt
then
    echo
    echo '----- REGRESSION TEST FAILED -----'
    echo
    exit 1
fi
