all : build data

#####

GOBUILD=go build -o $@ $^

build : $(DST)/01a $(DST)/01b

$(DST)/01a : $(SRC)/01a.go $(SRC)/01-entries.go
	$(GOBUILD)

$(DST)/01b : $(SRC)/01b.go $(SRC)/01-entries.go
	$(GOBUILD)

#####

COPYFILE=cp -f $^ $@

FORCE:;

data : FORCE $(DST)/input-01.txt

$(DST)/input-01.txt : $(SRC)/input-01.txt
	$(COPYFILE)

#####

test : all
	@$(SRC)/run-regression-test

validate-test : $(SRC)/puzzle-output.txt

$(SRC)/puzzle-output.txt : $(DST)/regression-test-output.txt
	$(COPYFILE)

#####

help : FORCE
	@echo "COMMANDS"
	@echo
	@echo "        all [default]"
	@echo "                1. build programs"
	@echo "                2. copy data files"
	@echo
	@echo "        build"
	@echo "                build programs"
	@echo
	@echo "        data"
	@echo "                copy data files"
	@echo
	@echo "        test"
	@echo "                1. build programs"
	@echo "                2. copy data files"
	@echo "                3. run programs and compare the result to valid output"
	@echo
	@echo "        validate-test"
	@echo "                mark new test output as valid output"
	@echo
	@echo "        help"
	@echo "                show this text"
	@echo
