all : build data

#####

GOBUILD=go build -o $@ $^

build : $(DST)/01a $(DST)/01b $(DST)/02 $(DST)/03 $(DST)/04 $(DST)/05 $(DST)/06

$(DST)/01a : $(SRC)/01a.go $(SRC)/01-entries.go
	$(GOBUILD)

$(DST)/01b : $(SRC)/01b.go $(SRC)/01-entries.go
	$(GOBUILD)

$(DST)/02 : $(SRC)/02.go $(SRC)/02-passwords.go
	$(GOBUILD)

$(DST)/03 : $(SRC)/03.go $(SRC)/03-treemap.go
	$(GOBUILD)

$(DST)/04 : $(SRC)/04.go $(SRC)/04-passport.go
	$(GOBUILD)

$(DST)/05 : $(SRC)/05.go
	$(GOBUILD)

$(DST)/06 : $(SRC)/06.go
	$(GOBUILD)

#####

COPYFILE=cp -f $^ $@

FORCE:;

data : FORCE $(DST)/input-01.txt $(DST)/input-02.txt $(DST)/input-03.txt $(DST)/input-04.txt $(DST)/input-05.txt $(DST)/input-06.txt

$(DST)/input-01.txt : $(SRC)/input-01.txt ; $(COPYFILE)
$(DST)/input-02.txt : $(SRC)/input-02.txt ; $(COPYFILE)
$(DST)/input-03.txt : $(SRC)/input-03.txt ; $(COPYFILE)
$(DST)/input-04.txt : $(SRC)/input-04.txt ; $(COPYFILE)
$(DST)/input-05.txt : $(SRC)/input-05.txt ; $(COPYFILE)
$(DST)/input-06.txt : $(SRC)/input-06.txt ; $(COPYFILE)

#####

test : all
	@$(SRC)/run-regression-test

validate-test : $(SRC)/puzzle-output.txt

$(SRC)/puzzle-output.txt : $(DST)/regression-test-output.txt
	$(COPYFILE)

#####

help : FORCE
	@echo "COMMANDS"
	@echo
	@echo "        all [default]"
	@echo "                1. build programs"
	@echo "                2. copy data files"
	@echo
	@echo "        build"
	@echo "                build programs"
	@echo
	@echo "        data"
	@echo "                copy data files"
	@echo
	@echo "        test"
	@echo "                1. build programs"
	@echo "                2. copy data files"
	@echo "                3. run programs and compare the result to valid output"
	@echo
	@echo "        validate-test"
	@echo "                mark new test output as valid output"
	@echo
	@echo "        help"
	@echo "                show this text"
	@echo
